### ISSUE TITLE
Usage with Certain Built-In Elements

### ISSUE THREAD

**Issue by michaelcpuckett** [mfreed7/declarative-shadow-dom#12]
Is there a description of the behavior when a declarative shadow root is declared for `<html>`/`<head>`/`<fieldset>`? I'm finding these will not become shadow roots.

**Comment by mfreed7** [comment]
Sure - declarative shadow roots have the same limitations as "normal" shadow roots. They can only be attached to the [specified list of elements](https://dom.spec.whatwg.org/#dom-element-attachshadow), which is:

- a valid custom element name
- "article", "aside", "blockquote", "body", "div", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "main", "nav", "p", "section", or "span"

**Comment by TechQuery** [comment]
@mfreed7 How can I get the closed shadow root of extended built-in tags?

```html
<blockquote is="better-quote">
    <template shadowrootmode="closed">
        💡<slot></slot>
    </template>
    Something...
</blockquote>
```

```js
class BetterQuote extends HTMLQuoteElement {
    #internal = this.attachInternals();  // throw an error as it's a built-in tag

    connectedCallback() {
        console.log(this.#internal.shadowRoot);
    }
}
customElement.define('better-quote', BetterQuote, { extends: 'blockquote' });
```

**Comment by mfreed7** [comment]
> @mfreed7 How can I get the closed shadow root of extended built-in tags?

Yeah, you're right in finding that this isn't possible. You can get the **shadow root** itself, using

`const shadow = this.attachShadow({mode:'closed'});`

but of course the shadow root will be **emptied** before being returned to you.

You might consider [raising an issue on WHATWG/html](https://github.com/whatwg/html/issues/new) about this, if you think it's a big deal. One issue is that customized built-in tags aren't well supported either, and the spec editor happens to work for the one browser that doesn't support them. So I wouldn't expect a ton of positive responses. 😄

**Comment by TechQuery** [comment]
> You can get the shadow root itself, using
> ```js
> const shadow = this.attachShadow({mode:'closed'});
> ```
> but of course the shadow root will be emptied before being returned to you.

@mfreed7 So I hook the original `HTMLElement​.​prototype​.​attachShadow()`, then store all shadow roots in a `WeakMap` for finding:
https://github.com/EasyWebApp/declarative-shadow-dom-polyfill/blob/5616dc89dd8c22c785da3ae53d7e26cff81a5810/source/index.ts#L7-L35
