### ISSUE TITLE
Shadow DOM streaming issue

### ISSUE THREAD

**Issue by YusakuNo1** [mfreed7/declarative-shadow-dom#17]
As Blink only renders after closing tag </template> comes (mentioned in [here](https://github.com/mfreed7/declarative-shadow-dom#timing-attach-the-shadow-on-opening-or-closing-template-tag)), it creates a big performance issue for SSR with streaming, which renders declarative shadow DOM in the server side and send back to the client side. We can tell the streaming creates issues for the closed shadow root, however, can we still allow the open shadow root to be rendered from the open tag? In this case, it boost the performance of web pages with pure Web Components.

**Comment by mfreed7** [comment]
> As Blink only renders after closing tag comes (mentioned in [here](https://github.com/mfreed7/declarative-shadow-dom#timing-attach-the-shadow-on-opening-or-closing-template-tag)), it creates a big performance issue for SSR with streaming, which renders declarative shadow DOM in the server side and send back to the client side. We can tell the streaming creates issues for the closed shadow root, however, can we still allow the open shadow root to be rendered from the open tag? In this case, it boost the performance of web pages with pure Web Components.

Actually, the issues, and the reason why we decided not to pursue a streaming version of DSD, are related to the HTML parser, and not to whether the shadow root is open or closed. For technical reasons, it's harder to modify the parser to support parsing into a shadow root directly, as compared to the current implementation which just moves things at the end.

Having said that, I do understand the strong desire to make DSD work with streaming, and there are some discussions that have recently been re-opened. If there's a consensus to be had that supports streaming, I'm open to it.

In the meantime, thanks for the bug, but I'm going to close it now.

**Comment by mfreed7** [comment]
Also note: in an amazing about-face, there’s consensus not only on the DSD feature, but also the [streaming version](https://github.com/whatwg/dom/issues/831#issuecomment-1270870977). Stay tuned, as it sounds like DSD will soon support streaming.
