### ISSUE TITLE
Add `HTMLLinkElement.prototype.use` to handle `adoptedStylesheets`

### ISSUE THREAD

**Issue by mantou132** [mfreed7/declarative-shadow-dom#22]
e.g:

```html
<template id="style1">
  <style>
    * {
      color: red;
    }
  </style>
</template>
<template id="style2">
  <style>
    * {
      background: blue;
    }
  </style>
</template>
<my-element>
  <template shadowrootmode="open">
    <p>MyElement</p>
    <link rel="stylesheet" use="style1"></link>
  </template>
</my-element>
<link rel="stylesheet" use="style1"></link>
<link rel="stylesheet" use="style2"></link>
```
On the parser side, the style1 stylesheet will be applied to `document` and `my-element#shadowRoot`, and the style2 stylesheet will be only applied to `document`.

Advantage:

1. Backward compatibility
2. Strong expression ability, corresponding to `DocumnetOrShadowRoot.adoptedStylesheets`
3. No duplicate code will be generated during serialization

## Serialization

For manual serialization of `adoptedStylesheets` while traversing the DOM, can control the `id` generation method. can also add argument option to `getInnerHTML` to specify the `id` generation method, e.g:

```ts
// Automatic generated
document.body.getInnerHTML({ convertAdoptedStylesheetsToTemplate: true })
// Specify generation method
document.body.getInnerHTML({ convertAdoptedStylesheetsToTemplate: Math.random })
```

**Comment by mantou132** [comment]
Other solution: let the `link` element `href` attribute support fragment-only URLs:

```html
<link rel="stylesheet" href="#style1" />
```

But this conflicts with the SVG `use` element and CSS: https://github.com/WICG/webcomponents/issues/772#issuecomment-438834060

**Comment by mfreed7** [comment]
Thanks for the suggestion, but this repo is probably not the best place to file it. Declarative shadow DOM is now [a web standard](https://html.spec.whatwg.org/multipage/scripting.html#attr-template-shadowrootmode), so new issues and suggestions should be raised on [the WHATWG repo](https://github.com/whatwg/html/issues/new/choose).
