### ISSUE TITLE
Simple Polyfill for setInnerHTML is wrong, cause dom parser also has "head"

### ISSUE THREAD

**Issue by jogibear9988** [mfreed7/declarative-shadow-dom#23]
With set innerHTML you could also assing, script, link and other tags, wich the dom parser will move into the "head" section

**Comment by mfreed7** [comment]
Thanks for the bug! Two notes:

1. This explainer is out of date anyway, and I've added a note to that effect. The feature has been standardized, so MDN or the spec itself should be the authority. For example, the function is now called `setHTML` and not `setInnerHTML`.

2. The polyfill should work correctly as-is. Note that it explicitly (and for exactly this reason) adds a `<pre>` tag around the contents, which triggers the body and avoids putting anything into the head, with a few exceptions that can't be avoided.

**Comment by TechQuery** [comment]
You can try the latest polyfill: https://github.com/EasyWebApp/declarative-shadow-dom-polyfill
