### ISSUE TITLE
supportsDeclarativeShadowDOM returns true for current non-implementing browsers

### ISSUE THREAD

**Issue by rictic** [mfreed7/declarative-shadow-dom#3]
The given function for feature detection:

```javascript
function supportsDeclarativeShadowDOM() {
  return 'shadowRoot' in HTMLTemplateElement.prototype;
}
```

This returns true for existing browsers, as `shadowRoot` is defined on Element.prototype

**Comment by mfreed7** [comment]
Hmm very good point. Suggestions for a better way to feature detect?

**Comment by rictic** [comment]
This works in Chrome canary with `--enable-blink-features=DeclarativeShadowDOM`, but setting `.innerHTML` to a string is not compatible with some [trusted types](https://github.com/w3c/webappsec-trusted-types) CSP configs, so it's not what we'd generally recommend:

```javascript
let hasNative;
export function hasNativeDeclarativeShadowRoots() {
  if (hasNative === undefined) {
    const div = document.createElement('div');
    div.innerHTML = `<div><template shadowroot="open"></template></div>`;
    hasNative = !!div.firstElementChild.shadowRoot;
  }
  return hasNative;
}
```

It would be good to have some reliable way to tell, so that polyfills of the feature can avoid walking the document for templates.

**Comment by mfreed7** [comment]
@domenic do you have any recommendations here? The original `'shadowRoot' in HTMLTemplateElement.prototype` suggestion already returns true. Have we, in the past, added hooks that are **just** for doing feature detection? I.e. I could see adding `'supportsDeclarativeShadowDOM' in HTMLTemplateElement.prototype` but that seems ugly.

**Comment by domenic** [comment]
```js
HTMLTemplateElement.prototype.hasOwnProperty("shadowRoot");
```

**Comment by mfreed7** [comment]
Thanks - that works! I've updated [the explainer](https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md#feature-detection-and-polyfilling) accordingly, but I still need to implement this in Chromium.
