### ISSUE TITLE
Intersection semantics with Scoped Registries

### ISSUE THREAD

**Issue by caridy** [mfreed7/declarative-shadow-dom#6]
Note: this is a follow up issue from the last meeting.

Although these two proposals are in early stages, we need to solve the intersection semantics. There are two main issues:

1. if a declarative shadow root is created, elements inside that shadow should not be upgraded with the global registry. a possible solution is to add a new attribute, similar to `mode` to indicate to the parser that a custom registry is going to be eventually associated to this shadow.

2. if the component is planning to reuse the instance of the declarative shadow root (which is ideal), how can the component associate that instance with a registry? this indicates that maybe the association between ShadowRoot and CustomElementRegistry cannot be defined via `attachShadow()`, and instead, something like `ElementInternals` might be much more flexible.

**Comment by caridy** [comment]
some other good info that might touch on this is being discussed here: https://github.com/w3c/webcomponents/issues/871

**Comment by mfreed7** [comment]
Thanks for the comments here. I agree with both points. But... since it seems like there are solutions to these problems that don't directly impact/change this Shadow DOM proposal, I'm starting to think that these concerns need to be wrapped into the proposal for Scoped Custom Element Registries. There, they can be thought through more fully. Would you agree?

+@justinfagnani

**Comment by caridy** [comment]
@mfreed7 I'm fine with that. I'm just waiting for @justinfagnani to either create the repo for the proposal, or let me know and I can take care of that, so we can help with it, and track things there.

**Comment by mfreed7** [comment]
Thanks @caridy. Based on your comment, I'm going to close this issue. Hopefully you can raise it with @justinfagnani.
