### ISSUE TITLE
Performance compared to custom element solution

### ISSUE THREAD

**Issue by drdreo** [mfreed7/declarative-shadow-dom#8]
I wanted to contact you regarding the performance results. Since I am currently evaluating the performance of my custom element solution for a declarative shadow root element I came across your benchmark which I used for my [tests](https://github.com/drdreo/declarative-shadow/tree/master/perf) as well. 

| Benchmark      | Bytes       | Avg. time           |
|----------------|-------------|---------------------|
| Custom Element | 1034.65 KiB | 222.76 - 224.84ms   |
| Native         | 1034.63 KiB | 248.72ms - 254.60ms |

I was wondering how the native implementation can be slower compared to a custom element solution. Do you know what can cause this or is there a plausible explanation which I can mention, since I do not believe a native solution would be slower?

**Comment by mfreed7** [comment]
Thanks for the comment here, and sorry for the delay responding. I'm a bit unclear on which specific test configs correspond to the entries in the table you provided above. [Your tachometer.json](https://github.com/drdreo/declarative-shadow/blob/master/perf/tachometer.json) looks exactly like mine, and has three test conditions. Can you elaborate a bit? Are you still experiencing this situation?

**Comment by drdreo** [comment]
No worries. 
When I have created this issue, I couldn't test the native performance myself. But since you were fiddling around with it in Chrome, I think I have gotten these numbers somewhere from an old proposal made by you and was curious how the native implemented DSD can result in these numbers, being worse than a custom element attaching the shadow. 

I think this is obsolete and can be closed now. Btw, thanks a lot for the work on this topic. Really good to see it happening.

**Comment by curiosdevcookie** [comment]
Yes, thank you so much! It was hilarious, almost like those stereotypical poor souls in movies who let everything they currently hold drop to the floor or forget how walking works/bump against lampposts, whenever they see their secret crush near… Well, upon hearing those good declarative news on Google’s Channel—I wasn’t outside, so no lamppost danger, however, dropping stuff was a very close miss. Couldn’t believe what I was hearing! Hurray! 🙆🏻‍♀️☀️😄
